# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6196cf23c9ca428fd6f4bd88dbfa3b81b3cb151009205dc7c63416c636fdaafae85ecc8bd977df965e802aa827a84438ab7c43de453010f9c05aace4277a78a8

test:
  secret_key_base: 73b9f5eeea47c9787eada857216fc867299aff3c105e86ef3fbec3a827e22a1e110909340cad889c45a0fbea7b3d07127e69cbea6e9564a97f27b441f3d16af9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
